import { Component, OnInit } from '@angular/core';
import { NavigationExtras, Route, Router } from '@angular/router';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Component({
  selector: 'app-landing-page',
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.scss']
})
export class LandingPageComponent implements OnInit {

  constructor(public route:Router) { }

  ngOnInit(): void {
  }

  forward(item:any){

    // this.route.navigate(['about/'+item]);
    this.route.navigateByUrl('/login')
  }

  update(){

  }
  heading = [['Sl No.', 'Group', 'Notice Content', 'From Date', 'To Date','Document','Status']];
  oh(){
    alert("hi")
    var doc = new jsPDF('l', 'mm',[297, 210]);
    doc.setFontSize(12);

    doc.text("Notification Details Report", 14, 10);
    doc.text('From Date :- ',14,20);
    doc.text('To Date:- ',14,30);
    doc.text('Group Name:- ' ,14,40);
    doc.text("Generated By: ", 14, 50);

    var rows = [];
    for(var i=0;i<2;i++) {
      var notdetails
      var pdf = [];
      pdf[0]=1
      // pdf[1] = notdetails.groupId;
      // pdf[2] = notdetails.noticeContent;
      // pdf[3] = notdetails.fromDate;
      // pdf[4] = notdetails.toDate;
      // pdf[5] = notdetails.document;
      // pdf[6] = notdetails.statusFlag;

      rows.push(pdf);
    }
    autoTable(doc, {
      head: this.heading,
      body: rows,
      theme: 'grid',
      startY: 60,
      //startX: 50,
      headStyles: {
        fillColor: [26, 99, 54]
      },
      columnStyles: {
        0: {cellWidth: 10},
        1: {cellWidth: 30},
        2: {cellWidth: 60},
        3: {cellWidth: 30},
        4: {cellWidth: 55},
        5: {cellWidth: 50},
        6: {cellWidth: 30},

        // 6: {cellWidth: 25},
        // 7: {cellWidth: 25},
        // 8: {cellWidth: 30},
        // 9: {cellWidth: 30},

      }
    });
    doc.save('BSKY_Notification Details Report.pdf');


  }



}

